version: 4
useFMTitle: true
useNoteTitleForLink: true
mermaid: true
useKatex: true
dev:
    enablePreviewV2: true
site:
    copyAssets: true
    siteHierarchies:
        - root
    siteRootDir: docs
    siteUrl: 'https://mapp-metabolomics-unit.github.io'
    assetsPrefix: /mapp-dws-public
    gh_edit_link: true
    gh_edit_link_text: Click here to edit this page on Github !
    gh_edit_repository: 'https://github.com/mapp-metabolomics-unit/mapp-dws-public'
    gh_edit_branch: main
    gh_edit_view_mode: edit
    siteLastModified: true
    usePrettyRefs: true
    title: MAPP Metabolomics Public Dendron
    description: Personal knowledge space
    duplicateNoteBehavior:
        action: useVault
        payload:
            - vault
commands:
    lookup:
        note:
            selectionMode: extract
            confirmVaultOnCreate: false
            leaveTrace: false
            bubbleUpCreateNew: true
    insertNote:
        initialValue: templates
    insertNoteLink:
        aliasMode: none
        enableMultiSelect: false
    insertNoteIndex:
        enableMarker: false
    randomNote: {}
workspace:
    vaults:
        -
            fsPath: vault
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
    scratch:
        name: scratch
        dateFormat: y.MM.dd.HHmmss
        addBehavior: asOwnDomain
    graph:
        zoomSpeed: 1
    enableAutoCreateOnDefinition: false
    enableXVaultWikiLink: false
    enableRemoteVaultInit: true
    workspaceVaultSyncMode: noCommit
    enableAutoFoldFrontmatter: true
    maxPreviewsCached: 10
    maxNoteLength: 204800
    task:
        name: ''
        dateFormat: ''
        addBehavior: childOfCurrent
        statusSymbols:
            '': ' '
            wip: w
            done: x
            assigned: a
            moved: m
            blocked: b
            delegated: l
            dropped: d
            pending: 'y'
        prioritySymbols:
            H: high
            M: medium
            L: low
        todoIntegration: false
        createTaskSelectionType: selection2link
    enableUserTags: true
    enableHashTags: true
    dendronVersion: 0.71.0
preview:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
